### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by CringyMan2137** [kashifulhaque/discord-bot-for-gcp#2]
i have this error while i type "npm start"

npm ERR! code 1
npm ERR! path C:\Users\pc\Desktop\discord COMPUTE MACHIN\discord-bot-for-gcp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "node index.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pc\AppData\Local\npm-cache\_logs\2021-01-12T12_04_32_958Z-debug.log

**Comment by CringyMan2137** [comment]
<img width="592" alt="error" src="https://user-images.githubusercontent.com/76834188/104312996-b0739a00-54d7-11eb-96a8-6865d66c56e5.PNG">

**Comment by kashifulhaque** [comment]
Hi, I am currently unavailable. I will get back to you as soon as possible. Sorry for the delay!

**Comment by CringyMan2137** [comment]
i readed README.md and nothing helped : (

**Comment by kashifulhaque** [comment]
Hi there, I just looked into your error.
GCP_config.json file is missing from your directory. You can read the README.md to know how to generate the GCP_config.json file

or

You can visit the link given below and follow the steps there. Do let me know if you face an issue.
Link to generate GCP_config.json: https://cloud.google.com/docs/authentication/production?_ga=2.205580179.1089106346.1589480557-1074299793.1585422711#obtaining_and_providing_service_account_credentials_manually

**Comment by CringyMan2137** [comment]
thanks! that fixed everything!

**Comment by kashifulhaque** [comment]
Glad I could help. Good Luck!
